apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring
data:
  config.yaml: |
    rules:
      - seriesQuery: 'predicted_traffic{namespace!="",pod!=""}'
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        name:
          matches: "predicted_traffic"
          as: "predicted_traffic"
        metricsQuery: 'sum(predicted_traffic{namespace="default"})'
