apiVersion: v1
kind: Service
metadata:
  name: ai-webapp
  namespace: default
  labels:
    app: ai-webapp
spec:
  selector:
    app: ai-webapp
  ports:
    - port: 80
      targetPort: 3000  # or whatever port your Node.js app exposes
      name: http
