apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-webapp
  labels:
    app: ai-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-webapp
  template:
    metadata:
      labels:
        app: ai-webapp
    spec:
      containers:
        - name: ai-webapp
          image: prakshiptha/ai-webapp:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
