apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-webapp-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ai-webapp
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
